stages:
  cs-shapley-fetch-data:
    matrix:
      dataset: ${active.datasets}
    cmd: python -m scripts.fetch_data --dataset-name ${item.dataset}
    deps:
      - scripts/fetch_data.py
    outs:
      - output/raw/${item.dataset}

  cs-shapley-preprocess-data:
    matrix:
      dataset: ${active.datasets}
    cmd: python -m scripts.preprocess_data --dataset-name ${item.dataset}
    deps:
      - scripts/preprocess_data.py
      - output/raw/${item.dataset}
    outs:
      - output/preprocessed/${item.dataset}

  cs-shapley-wad-drop-experiment:
    matrix:
      dataset: ${active.datasets}
      model: ${active.models}
    cmd: python -m scripts.run_experiment_wad_drop --dataset-name ${item.dataset} --model-name ${item.model}
    deps:
      - scripts/run_experiment_wad_drop.py
      - output/preprocessed/${item.dataset}
    outs:
      - output/results/wad_drop/${item.model}/${item.dataset}

  cs-shapley-wad-drop-plots:
    matrix:
      model: ${active.models}
    cmd: python -m scripts.render_plots --experiment-name wad_drop --model-name ${item.model}
    deps:
      - scripts/render_plots.py
      - output/results/wad_drop/${item.model}

  cs-shapley-noise-removal-experiment:
    matrix:
      dataset: ${active.datasets}
      model: ${active.models}
    cmd: python -m scripts.run_experiment_noise_removal --dataset-name ${item.dataset} --model-name ${item.model}
    deps:
      - scripts/run_experiment_noise_removal.py
      - output/preprocessed/${item.dataset}
    outs:
      - output/results/noise_removal/${item.model}/${item.dataset}

  cs-shapley-noise-removal-plots:
    matrix:
      model: ${active.models}
    cmd: python -m scripts.render_plots --experiment-name noise_removal --model-name ${item.model}
    deps:
      - scripts/render_plots.py
      - output/results/noise_removal/${item.model}

  cs-shapley-wad-drop-transfer-experiment:
    matrix:
      dataset: ${active.datasets}
      model: ${active.models}
      transfer_model: ${experiments.wad_drop_transfer.transfer_models}
    cmd: python -m scripts.run_experiment_wad_drop --dataset-name ${item.dataset} --model-name ${item.model} --transfer-model-name ${item.transfer_model}
    deps:
      - scripts/run_experiment_wad_drop.py
      - output/preprocessed/${item.dataset}
    outs:
      - output/results/wad_drop_transfer/${item.model}/${item.transfer_model}/${item.dataset}

  cs-shapley-wad-drop-transfer-plots:
    matrix:
      model: ${active.models}
      transfer_model: ${experiments.wad_drop_transfer.transfer_models}

    cmd: python -m scripts.render_plots --experiment-name wad_drop_transfer --model-name ${item.model} --sub-folder ${item.transfer_model}
    deps:
      - scripts/render_plots.py
      - output/results/wad_drop_transfer/${item.model}/${item.transfer_model}