vars:
  - activated_datasets: [
      "click",
      "diabetes",
      "phoneme",
      "fmnist_binary",
      "mnist_binary",
      "mnist_multi"
    ]

stages:
  data-valuation-fetch-data:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.fetch_data --dataset-name ${key}
      deps:
      - scripts/fetch_data.py
      params:
        - datasets
        - datasets.${key}
      outs:
      - output/raw/${key}  # TODO: Change to openml_id

  data-valuation-preprocess-data:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.preprocess_data --dataset-name ${key}
      deps:
      - scripts/preprocess_data.py
      - output/raw/${key}
      params:
        - datasets
        - datasets.${key}
      outs:
      - output/preprocessed/${key}

  data-valuation-wad-drop-run-experiment:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.run_experiment wad_drop --dataset-name ${key}
      deps:
      - scripts/run_experiments.py
      - output/preprocessed/${key}
      outs:
      - output/results/wad_drop/${key}

  data-valuation-wad-drop-generate-plots:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.generate_plots wad_drop --dataset-name ${key}
      deps:
        - scripts/generate_plots.py
        - output/results/wad_drop/${key}
      outs:
        - output/plots/wad_drop/${key}

  data-valuation-noise-removal-run-experiment:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.run_experiment noise_removal --dataset-name ${key}
      deps:
        - scripts/run_experiments.py
        - output/preprocessed/${key}
      outs:
        - output/results/noise_removal/${key}

  data-valuation-noise-removal-generate-plots:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.generate_plots noise_removal --dataset-name ${key}
      deps:
        - scripts/generate_plots.py
        - output/results/noise_removal/${key}
      outs:
        - output/plots/noise_removal/${key}

  data-valuation-wad-drop-transfer-run-experiment:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.run_experiment wad_drop_transfer --dataset-name ${key}
      deps:
        - scripts/run_experiments.py
        - output/preprocessed/${key}
      outs:
        - output/results/wad_drop_transfer/${key}

  data-valuation-wad-drop-transfer-generate-plots:
    foreach: ${datasets}
    do:
      cmd: python -m scripts.generate_plots wad_drop_transfer --dataset-name ${key}
      deps:
        - scripts/generate_plots.py
        - output/results/wad_drop_transfer/${key}
      outs:
        - output/plots/wad_drop_transfer/${key}