stages:
  data-valuation-fetch-data:
    cmd: python -m src.csshapley22.experiments.fetch_data
    deps:
    - src/csshapley22/experiments/fetch_data.py
    outs:
    - output/raw

  data-valuation-preprocess-data:
    cmd: python -m src.csshapley22.experiments.preprocess_data
    deps:
    - src/csshapley22/experiments/preprocess_data.py
    - output/raw
    outs:
    - output/preprocessed