stages:
  cs-shapley-fetch-data:
    matrix:
      dataset: ${active.datasets}
    cmd: python -m scripts.fetch_data --dataset-name ${item.dataset}
    deps:
      - scripts/fetch_data.py
    outs:
      - output/raw/${item.dataset}

  cs-shapley-preprocess-data:
    matrix:
      dataset: ${active.datasets}
    cmd: python -m scripts.preprocess_data --dataset-name ${item.dataset}
    deps:
      - scripts/preprocess_data.py
      - output/raw/${item.dataset}
    outs:
      - output/preprocessed/${item.dataset}

  cs-shapley-wad-drop-experiment:
    matrix:
      dataset: ${active.datasets}
      model: ${active.models}
    cmd: python -m scripts.run_experiment_wad_drop --dataset-name ${item.dataset} --model-name ${item.model}
    deps:
      - scripts/run_experiment_wad_drop.py
      - output/preprocessed/${item.dataset}
    outs:
      - output/results/wad_drop/${item.model}/${item.dataset}

  cs-shapley-noise-removal-experiment:
    matrix:
      dataset: ${active.datasets}
      model: ${active.models}
    cmd: python -m scripts.run_experiment_noise_removal --dataset-name ${item.dataset} --model-name ${item.model}
    deps:
      - scripts/run_experiment_noise_removal.py
      - output/preprocessed/${item.dataset}
    outs:
      - output/results/noise_removal/${item.model}/${item.dataset}

#  data-valuation-wad-drop-generate-plots:
#    foreach: ${datasets}
#    do:
#      cmd: python -m scripts.render_plots wad_drop --dataset-name ${key}
#      deps:
#        - scripts/render_plots.py
#        - output/results/wad_drop/${key}
#      outs:
#        - output/plots/wad_drop/${key}

#  data-valuation-noise-removal-run-experiment:
#    foreach: ${datasets}
#    do:
#      cmd: python -m scripts.run_experiment noise_removal --dataset-name ${key}
#      deps:
#        - scripts/run_experiment.py
#        - output/preprocessed/${key}
#      outs:
#        - output/results/noise_removal/${key}

#  data-valuation-noise-removal-generate-plots:
#    foreach: ${datasets}
#    do:
#      cmd: python -m scripts.render_plots noise_removal --dataset-name ${key}
#      deps:
#        - scripts/render_plots.py
#        - output/results/noise_removal/${key}
#      outs:
#        - output/plots/noise_removal/${key}

#  data-valuation-wad-drop-transfer-run-experiment:
#    foreach: ${datasets}
#    do:
#      cmd: python -m scripts.run_experiment wad_drop_transfer --dataset-name ${key}
#      deps:
#        - scripts/run_experiment.py
#        - output/preprocessed/${key}
#      outs:
#        - output/results/wad_drop_transfer/${key}
#
#  data-valuation-wad-drop-transfer-generate-plots:
#    foreach: ${datasets}
#    do:
#      cmd: python -m scripts.render_plots wad_drop_transfer --dataset-name ${key}
#      deps:
#        - scripts/render_plots.py
#        - output/results/wad_drop_transfer/${key}
#      outs:
#        - output/plots/wad_drop_transfer/${key}