stages:
  data-valuation-fetch-data:
    cmd: python -m src.csshapley22.stages.fetch_data
    deps:
    - src/csshapley22/stages/fetch_data.py
    outs:
    - output/raw

  data-valuation-preprocess-data:
    cmd: python -m src.csshapley22.stages.preprocess_data
    deps:
    - src/csshapley22/stages/preprocess_data.py
    - output/raw
    outs:
    - output/preprocessed

  data-valuation-run-experiments:
    cmd: python -m src.csshapley22.stages.run_experiments
    deps:
    - src/csshapley22/stages/run_experiments.py
    - output/preprocessed
    outs:
    - output/results

  data-valuation-generate-plots:
    cmd: python -m src.csshapley22.stages.generate_plots
    deps:
    - src/csshapley22/stages/generate_plots.py
    - output/results
    outs:
    - output/plots