settings:
  n_jobs: 92
  backend: joblib

active:
  experiments: [
    point_removal,
    noise_removal
  ]
  models: [
    logistic_regression,
    svm,
    knn
  ]
  datasets: [
    diabetes,
    cpu,
    click,
    covertype,
    cifar10,
    fmnist_binary,
    mnist_binary,
    mnist_multi,
    phoneme
  ]
  valuation_methods: [
    random,
    loo,
    classwise_shapley,
    beta_shapley,
    tmc_shapley,
    banzhaf_shapley,
    owen_sampling_shapley,
    least_core
  ]
  repetitions: [ 1, 2, 3, 4, 5 ]

experiments:
  point_removal:
    sampler: default
    metrics:
      weighted_accuracy_drop_logistic_regression:
        idx: weighted_metric_drop
        metric: accuracy
        eval_model: logistic_regression
      weighted_accuracy_drop_knn:
        idx: weighted_metric_drop
        metric: accuracy
        eval_model: knn
      weighted_accuracy_drop_gradient_boosting_classifier:
        idx: weighted_metric_drop
        metric: accuracy
        eval_model: gradient_boosting_classifier
      weighted_accuracy_drop_svm:
        idx: weighted_metric_drop
        metric: accuracy
        eval_model: svm
      weighted_accuracy_drop_mlp:
        idx: weighted_metric_drop
        metric: accuracy
        eval_model: mlp
  
  noise_removal:
    sampler: default
    preprocessors:
      flip_labels:
        perc: 0.2
    metrics:
      roc_auc:
        idx: precision_recall_roc_auc
        flipped_labels: preprocessor.flip_labels.idx

samplers:
  default:
    train: 0.1667
    val: 0.1667
    test: 0.6667
    max_samples: 3000

datasets:
  diabetes:
    openml_id: 37
  
  cpu:
    openml_id: 197
    preprocessor:
      threshold_y:
        threshold: 89
  
  click:
    openml_id: 1216
  
  covertype:
    openml_id: 1596
  
  phoneme:
    openml_id: 1489
  
  fmnist_binary:
    openml_id: 40996
    filters:
      binarization:
        label_zero: "0"
        label_one: "1"
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: True
        seed: 101
  
  cifar10:
    openml_id: 40927
    filters:
      binarization:
        label_zero: "1"
        label_one: "9"
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: False
        seed: 102
  
  mnist_binary:
    openml_id: 554
    filters:
      binarization:
        label_zero: "1"
        label_one: "7"
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: True
        seed: 103

  mnist_multi:
    openml_id: 554
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: True
        seed: 104

models:
  logistic_regression:
    solver: liblinear
  
  gradient_boosting_classifier:
    n_estimators: 1
    min_samples_leaf: 6
    max_depth: 2
  
  knn:
    n_neighbors: 5
    weights: uniform
  
  svm:
    kernel: rbf
  
  mlp: { }

valuation_methods:
  random:
    algorithm: "random"
  
  loo:
    algorithm: "loo"
    kwargs:
      progress: True
  
  classwise_shapley:
    algorithm: "classwise_shapley"
    kwargs:
      n_updates: 500
      normalize_values: True
      n_resample_complement_sets: 1
      use_default_scorer_value: False
      rtol: 1e-4
      progress: True
  
  
  beta_shapley:
    algorithm: "beta_shapley"
    kwargs:
      alpha: 16.0
      beta: 1.0
      n_updates: 500
      progress: True
  
  
  banzhaf_shapley:
    algorithm: "banzhaf_shapley"
    kwargs:
      n_updates: 500
      progress: True
  
  
  tmc_shapley:
    algorithm: "tmc_shapley"
    kwargs:
      rtol: 1e-4
      n_updates: 500
      progress: True
  
  
  owen_sampling_shapley:
    algorithm: "owen_sampling_shapley"
    kwargs:
      n_updates: 10
      max_q: 50
      progress: False
  
  
  least_core:
    algorithm: "least_core"
    kwargs:
      n_updates: 5000
      progress: False
    
  