
experiment_3:
  test_models: [
    "logistic_regression"
  ]

general:

  n_repetitions: 3

  models:

    logistic_regression: {
      solver: liblinear,
      n_jobs: 1
    }

    gradient_boosting_classifier: {
      n_estimators: 32
    }

  valuation_methods:

    cs_shapley: {
      n_updates: 50
    }

    beta_shapley: {
      alpha: 1,
      beta: 16,
      n_updates: 50
    }

  datasets:

    diabetes: {
      openml_id: 37,
      train_size: 128,
      dev_size: 128,
      test_size: 512
    }

    click: {
      openml_id: 1216,
      train_size: 500,
      dev_size: 500,
      test_size: 2000,
    }
