global:
  n_repetitions: 3
  n_jobs: 40
  backend: joblib
  temp_dir: /raid/tmp/ray

experiments:
  wad_drop:
  noise_removal:
  wad_drop_transfer:
    transfer_models:
      logistic_regression: {
        solver: liblinear,
      }
      gradient_boosting_classifier: {
        n_estimators: 40,
        min_samples_leaf: 6,
        max_depth: 2
      }
#      knn: {
#        n_neighbors: 5,
#        weights: uniform
#      }
#      svm: {
#        kernel: rbf
#      }
#      mlp: {
#
#      }

models:
  logistic_regression: {
    solver: liblinear,
  }
#  knn: {
#    n_neighbors: 5,
#    weights: uniform
#  }
#  svm: {
#    kernel: rbf
#  }

valuation_methods:
#  random: {
#    valuation_method: "random",
#  }
#  loo: {
#    valuation_method: "loo",
#    progress: False
#  }
  classwise_shapley: {
    valuation_method: "classwise_shapley",
    n_updates: 500,
    normalize_values: True,
    n_resample_complement_sets: 10,
    rtol: 1e-4,
    progress: True
  }
  classwise_shapley_add_idx: {
    valuation_method: "classwise_shapley",
    n_updates: 500,
    normalize_values: True,
    n_resample_complement_sets: 10,
    use_default_scorer_value: False,
    rtol: 1e-4,
    progress: True
  }
#  beta_shapley: {
#    valuation_method: "beta_shapley",
#    alpha: 16.0,
#    beta: 1.0,
#    n_updates: 1000,
#    progress: False
#  }
#  tmc_shapley: {
#    valuation_method: "tmc_shapley",
#    rtol: 1e-4,
#    n_updates: 1000,
#    progress: False
#  }

datasets:
  diabetes: {
    openml_id: 37,
    train_size: 128,
    dev_size: 128,
    test_size: 512
  }
  cpu: {
    openml_id: 197,
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
    preprocessor: {
      threshold_y: {
        threshold: 89,
      }
    },
  }
  click: {
    openml_id: 1216,
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  covertype: {
    openml_id: 1596,
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  phoneme: {
    openml_id: 1489,
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  fmnist_binary: {
    openml_id: 40996,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: True
      }
    },
    filters: {
      binarization: {
        label_zero: "0",
        label_one: "1"
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  cifar10: {
    openml_id: 40927,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: False
      }
    },
    filters: {
      binarization: {
        label_zero: "1",
        label_one: "9"
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000
  }
  mnist_binary: {
    openml_id: 554,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: True
      }
    },
    filters: {
      binarization: {
        label_zero: "1",
        label_one: "7"
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000
  }
  mnist_multi: {
    openml_id: 554,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: True
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000
  }