global:
  n_repetitions: 5
  n_jobs: 5
  backend: ray
  temp_dir: /raid/tmp/ray

experiments:
  wad_drop:
  noise_removal:
  wad_drop_transfer:
    transfer_models:
      logistic_regression: {
        solver: liblinear,
      }
      gradient_boosting_classifier: {
        n_estimators: 40,
        min_samples_leaf: 6,
        max_depth: 2
      }
      knn: {
        n_neighbors: 5,
        weights: uniform
      }
      svm: {
        kernel: rbf
      }
      mlp: {

      }

models:
  logistic_regression: {
    solver: liblinear,
  }
  gradient_boosting_classifier: {
    n_estimators: 40,
    min_samples_leaf: 6,
    max_depth: 2
  }
  knn: {
    n_neighbors: 5,
    weights: uniform
  }
  svm: {
    kernel: rbf
  }

valuation_methods:
  classwise_shapley: {
    n_updates: 500,
    normalize_values: True,
    n_resample_complement_sets: 3,
    rtol: 1e-4,
    progress: True
  }
  loo: {
    progress: True
  }
  beta_shapley: {
    alpha: 16.0,
    beta: 1.0,
    n_updates: 500,
    progress: True
  }
  tmc_shapley: {
    rtol: 1e-4,
    n_updates: 500,
    progress: True
  }

datasets:
  diabetes: {
    openml_id: 37,
    train_size: 128,
    dev_size: 128,
    test_size: 512
  }
  click: {
    openml_id: 1216,
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  phoneme: {
    openml_id: 1489,
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  fmnist_binary: {
    openml_id: 40996,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: True
      }
    },
    filters: {
      binarization: {
        label_zero: "0",
        label_one: "1"
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000,
  }
  cifar10: {
    openml_id: 40927,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: False
      }
    },
    filters: {
      binarization: {
        label_zero: "1",
        label_one: "9"
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000
  }
  mnist_binary: {
    openml_id: 554,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: True
      }
    },
    filters: {
      binarization: {
        label_zero: "1",
        label_one: "7"
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000
  }
  mnist_multi: {
    openml_id: 554,
    preprocessor: {
      principal_resnet_components: {
        n_components: 32,
        grayscale: True
      }
    },
    train_size: 500,
    dev_size: 500,
    test_size: 2000
  }