settings:
  n_jobs: 95
  backend: joblib
  mlflow_tracking_uri: http://localhost:5000

  stages:
    fetch_data: false
    preprocess_data: false
    sample_data: false
    calculate_values: false
    calculate_threshold_characteristics: false
    evaluate_curves: true
    evaluate_metrics: true
    render_plots: true


  time:
    active: true

  threshold_characteristics:
    active: false
    valuation_method: banzhaf_shapley  # Method used to calculate the threshold characteristics.
    model: logistic_regression  # Default model to use for determining the values
    max_plotting_percentage: 1e-4  # Threshold for stopping plotting in direction of x-axis.

active:
  experiments:
  - point_removal
  - noise_removal
  models:
  - logistic_regression
  - knn
  - svm
  - gradient_boosting_classifier
  datasets:
  - cifar10
  - click
  - covertype
  - cpu
  - diabetes
  - fmnist_binary
  - mnist_binary
  - mnist_multi
  - phoneme
  valuation_methods:
  - random
  - classwise_shapley
  - tmc_shapley
  - beta_shapley
  - banzhaf_shapley
  - least_core
  - loo
  repetitions:
    from: 1
    to: 20

experiments:
  point_removal:
    sampler: default
    curves:
      weighted_accuracy_drop_logistic_regression:
        fn: metric
        metric: accuracy
        eval_model: logistic_regression
        plots:
          - accuracy
      weighted_accuracy_drop_knn:
        fn: metric
        metric: accuracy
        eval_model: knn
        plots:
          - accuracy
      weighted_accuracy_drop_gradient_boosting_classifier:
        fn: metric
        metric: accuracy
        eval_model: gradient_boosting_classifier
        plots:
          - accuracy
      weighted_accuracy_drop_svm:
        fn: metric
        metric: accuracy
        eval_model: svm
        plots:
          - accuracy
      weighted_accuracy_drop_mlp:
        fn: metric
        metric: accuracy
        eval_model: mlp
        plots:
          - accuracy

    metrics:
      geometric_weighted_drop:
        curve:
          - weighted_accuracy_drop_logistic_regression
          - weighted_accuracy_drop_knn
          - weighted_accuracy_drop_gradient_boosting_classifier
          - weighted_accuracy_drop_svm
          - weighted_accuracy_drop_mlp
        fn: geometric_weighted_drop
        input_perc: 1.0
        plots:
          - table_wad
          - box_wad

      geometric_weighted_drop_half:
        curve:
          - weighted_accuracy_drop_logistic_regression
          - weighted_accuracy_drop_knn
          - weighted_accuracy_drop_gradient_boosting_classifier
          - weighted_accuracy_drop_svm
          - weighted_accuracy_drop_mlp
        fn: geometric_weighted_drop
        input_perc: 0.5
        plots:
          - table_wad
          - box_wad

  noise_removal:
    sampler: default
    preprocessors:
      flip_labels:
        perc: 0.2
    curves:
      precision_recall:
        fn: precision_recall
        flipped_labels: preprocessor.flip_labels.idx
        plots:
          - precision_recall
    metrics:
      roc_auc:
        curve:
          - precision_recall
        fn: roc_auc
        plots:
          - table_auc
          - box_auc

plots:
  accuracy:
    type: line
    plot_perc: 0.5
    x_label: "n"
    y_label: "Accuracy"

  precision_recall:
    type: line
    x_label: "Recall"
    y_label: "Precision"

  table_wad:
    type: table

  table_auc:
    type: table

  box_wad:
    type: boxplot
    x_label: "WAD"

  box_auc:
    type: boxplot
    x_label: "AUC"


samplers:
  default:
    train: 0.1667
    val: 0.1667
    test: 0.6667
    max_samples: 3000

datasets:
  diabetes:
    openml_id: 37

  cpu:
    openml_id: 197
    preprocessor:
      threshold_y:
        threshold: 89

  click:
    openml_id: 1216

  covertype:
    openml_id: 1596

  phoneme:
    openml_id: 1489

  fmnist_binary:
    openml_id: 40996
    filters:
      binarization:
        label_zero: '0'
        label_one: '1'
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: true
        seed: 101

  cifar10:
    openml_id: 40927
    filters:
      binarization:
        label_zero: '1'
        label_one: '9'
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: false
        seed: 102

  mnist_binary:
    openml_id: 554
    filters:
      binarization:
        label_zero: '1'
        label_one: '7'
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: true
        seed: 103

  mnist_multi:
    openml_id: 554
    preprocessor:
      principal_resnet_components:
        n_components: 32
        grayscale: true
        seed: 104

models:
  logistic_regression:
    model: logistic_regression
    solver: liblinear

  gradient_boosting_classifier:
    model: gradient_boosting_classifier
    n_estimators: 40
    min_samples_split: 6
    max_depth: 2

  knn:
    model: knn
    n_neighbors: 5
    weights: uniform

  svm:
    model: svm
    kernel: rbf

  mlp:
    model: mlp

valuation_methods:
  random:
    algorithm: random

  loo:
    algorithm: loo
    progress: true
    cache_group: acc

  classwise_shapley:
    algorithm: classwise_shapley
    cache_group: disc_acc
    normalize_values: true
    n_resample_complement_sets: 1
    n_updates: 500
    rtol: 1e-4
    progress: true
    use_default_scorer_value: false

  beta_shapley:
    algorithm: beta_shapley
    alpha: 16.0
    beta: 1.0
    n_updates: 500
    progress: true
    cache_group: acc

  banzhaf_shapley:
    algorithm: banzhaf_shapley
    n_updates: 500
    progress: true
    cache_group: acc


  tmc_shapley:
    algorithm: tmc_shapley
    rtol: 1e-4
    n_updates: 500
    progress: true
    cache_group: acc

  least_core:
    algorithm: least_core
    n_updates: 5000
    progress: false
    cache_group: acc

