experiment_one:
  valuation_methods:

    class_wise:
    leave_one_out:
    truncated_monte_carlo:

  datasets:
    diabetes:
      train_size: 128
      dev_size: 128
      test_size: 512

    click:
      train_size: 500
      dev_size: 500
      test_size: 2000

    cpu:
      train_size: 500
      dev_size: 500
      test_size: 2000

    covertype:
      train_size: 500
      dev_size: 500
      test_size: 2000

    phoneme:
      train_size: 500
      dev_size: 500
      test_size: 2000

  settings:
    n_repetitions: 3
