experiment_one:
  valuation_methods:

    class_wise:
    leave_one_out:
    truncated_monte_carlo:

  datasets:
    click:
      train_size: 0.8

    diabetes:
      train_size: 0.8

  settings:
    n_repetitions: 3
